import beachEntryTexture from "@/assets/images/beach-entry.png";
import beachHomesTexture from "@/assets/images/beach-homes.jpg";
import beachPathTexture from "@/assets/images/beach-path.jpg";

export type DiscoverListing = {
  id: string;
  name: string;
  area: string;
  community: string;
  bedrooms: number;
  bathrooms: number;
  sleeps: number;
  kingBeds: number;
  queenBeds: number;
  privatePool: boolean;
  beachfront: boolean;
  golfCart: boolean;
  petsAllowed: boolean;
  accessible: boolean;
  elevator: boolean;
  previewImages: string[];
  typicalPrice: string;
};

export const googleMapsApiKey =
  (import.meta.env.GOOGLE_MAPS_JS_KEY as string | undefined) ??
  (import.meta.env.GOOGLE_MAPS_API_KEY as string | undefined) ??
  (import.meta.env.VITE_GOOGLE_MAPS_API_KEY as string | undefined);

export const sampleListings: DiscoverListing[] = [
  {
    id: "casa-del-sol",
    name: "Casa del Sol",
    area: "Santa Rosa Beach",
    community: "WaterColor",
    bedrooms: 5,
    bathrooms: 4,
    sleeps: 12,
    kingBeds: 3,
    queenBeds: 2,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: true,
    accessible: false,
    elevator: true,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$8.2k - $11.4k",
  },
  {
    id: "dune-horizon",
    name: "Dune Horizon",
    area: "Santa Rosa Beach",
    community: "Blue Mountain",
    bedrooms: 4,
    bathrooms: 3,
    sleeps: 10,
    kingBeds: 2,
    queenBeds: 1,
    privatePool: false,
    beachfront: true,
    golfCart: false,
    petsAllowed: false,
    accessible: true,
    elevator: false,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$6.9k - $9.7k",
  },
  {
    id: "rose-court-retreat",
    name: "Rose Court Retreat",
    area: "Inlet Beach",
    community: "Rosemary Beach",
    bedrooms: 4,
    bathrooms: 3,
    sleeps: 11,
    kingBeds: 3,
    queenBeds: 1,
    privatePool: false,
    beachfront: false,
    golfCart: true,
    petsAllowed: true,
    accessible: false,
    elevator: false,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$7.4k - $10.2k",
  },
  {
    id: "seaside-azure",
    name: "Seaside Azure",
    area: "Seaside",
    community: "Seaside",
    bedrooms: 4,
    bathrooms: 4,
    sleeps: 10,
    kingBeds: 2,
    queenBeds: 2,
    privatePool: false,
    beachfront: false,
    golfCart: true,
    petsAllowed: true,
    accessible: false,
    elevator: false,
    previewImages: [beachHomesTexture, beachEntryTexture, beachPathTexture],
    typicalPrice: "$7.8k - $11.1k",
  },
  {
    id: "watercolor-pines",
    name: "WaterColor Pines",
    area: "Santa Rosa Beach",
    community: "WaterColor",
    bedrooms: 5,
    bathrooms: 5,
    sleeps: 12,
    kingBeds: 3,
    queenBeds: 1,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: true,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$10.5k - $14.2k",
  },
  {
    id: "prominence-dunes",
    name: "Prominence Dunes",
    area: "WaterSound",
    community: "Prominence",
    bedrooms: 3,
    bathrooms: 3,
    sleeps: 8,
    kingBeds: 1,
    queenBeds: 2,
    privatePool: false,
    beachfront: false,
    golfCart: true,
    petsAllowed: true,
    accessible: false,
    elevator: false,
    previewImages: [beachEntryTexture, beachPathTexture, beachHomesTexture],
    typicalPrice: "$5.8k - $8.6k",
  },
  {
    id: "watersound-surf",
    name: "WaterSound Surf",
    area: "WaterSound",
    community: "WaterSound Beach",
    bedrooms: 4,
    bathrooms: 4,
    sleeps: 10,
    kingBeds: 2,
    queenBeds: 1,
    privatePool: true,
    beachfront: true,
    golfCart: false,
    petsAllowed: false,
    accessible: true,
    elevator: true,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$11.9k - $16.4k",
  },
  {
    id: "alys-courtyard",
    name: "Alys Courtyard",
    area: "Alys Beach",
    community: "Alys Beach",
    bedrooms: 4,
    bathrooms: 4,
    sleeps: 9,
    kingBeds: 2,
    queenBeds: 1,
    privatePool: true,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: true,
    previewImages: [beachPathTexture, beachEntryTexture, beachHomesTexture],
    typicalPrice: "$12.1k - $17.8k",
  },
  {
    id: "seacrest-boardwalk",
    name: "Seacrest Boardwalk",
    area: "Seacrest Beach",
    community: "Seacrest Beach",
    bedrooms: 4,
    bathrooms: 3,
    sleeps: 10,
    kingBeds: 2,
    queenBeds: 2,
    privatePool: false,
    beachfront: false,
    golfCart: true,
    petsAllowed: true,
    accessible: false,
    elevator: false,
    previewImages: [beachHomesTexture, beachEntryTexture, beachPathTexture],
    typicalPrice: "$7.2k - $9.9k",
  },
  {
    id: "rosemary-terrace",
    name: "Rosemary Terrace",
    area: "Rosemary Beach",
    community: "Rosemary Beach",
    bedrooms: 5,
    bathrooms: 4,
    sleeps: 12,
    kingBeds: 3,
    queenBeds: 1,
    privatePool: true,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: true,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$9.4k - $13.3k",
  },
  {
    id: "grayton-bungalow",
    name: "Grayton Bungalow",
    area: "Grayton Beach",
    community: "Seaside",
    bedrooms: 3,
    bathrooms: 2,
    sleeps: 8,
    kingBeds: 1,
    queenBeds: 1,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: true,
    accessible: false,
    elevator: false,
    previewImages: [beachPathTexture, beachEntryTexture, beachHomesTexture],
    typicalPrice: "$4.8k - $6.7k",
  },
  {
    id: "blue-mountain-overlook",
    name: "Blue Mountain Overlook",
    area: "Blue Mountain Beach",
    community: "Prominence",
    bedrooms: 4,
    bathrooms: 3,
    sleeps: 9,
    kingBeds: 2,
    queenBeds: 1,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: true,
    accessible: true,
    elevator: false,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$6.6k - $9.1k",
  },
  {
    id: "seagrove-sands",
    name: "Seagrove Sands",
    area: "Seagrove Beach",
    community: "Seaside",
    bedrooms: 4,
    bathrooms: 3,
    sleeps: 10,
    kingBeds: 2,
    queenBeds: 1,
    privatePool: false,
    beachfront: false,
    golfCart: true,
    petsAllowed: true,
    accessible: false,
    elevator: false,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$7.1k - $9.8k",
  },
  {
    id: "inlet-lighthouse",
    name: "Inlet Lighthouse",
    area: "Inlet Beach",
    community: "Rosemary Beach",
    bedrooms: 5,
    bathrooms: 4,
    sleeps: 11,
    kingBeds: 3,
    queenBeds: 1,
    privatePool: true,
    beachfront: true,
    golfCart: false,
    petsAllowed: false,
    accessible: true,
    elevator: true,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$10.9k - $15.3k",
  },
  {
    id: "watersound-west-bluff",
    name: "WaterSound West Bluff",
    area: "WaterSound",
    community: "WaterSound West Beach",
    bedrooms: 4,
    bathrooms: 3,
    sleeps: 9,
    kingBeds: 2,
    queenBeds: 1,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: true,
    accessible: false,
    elevator: false,
    previewImages: [beachHomesTexture, beachEntryTexture, beachPathTexture],
    typicalPrice: "$8.6k - $12.4k",
  },
];

export const known30AAreas = ["West 30A", "Central 30A", "East 30A"];

export const known30ACommunities = [
  "WaterColor",
  "Seaside",
  "Prominence",
  "WaterSound West Beach",
  "WaterSound Beach",
  "Seacrest Beach",
  "Alys Beach",
  "Rosemary Beach",
];

export const communityBeachAreaMap: Record<string, string> = {
  Seaside: "Seagrove Beach",
  WaterColor: "Seagrove Beach",
  "Seacrest Beach": "Seacrest Beach",
  "Rosemary Beach": "Rosemary / Inlet Beach",
  "Alys Beach": "Inlet Beach",
  "WaterSound Beach": "Inlet Beach",
  "Kaiya Beach Resort": "Inlet Beach",
};

export const geoByCommunity: Record<string, { lat: number; lng: number }> = {
  Seaside: { lat: 30.3234, lng: -86.1388 },
  WaterColor: { lat: 30.3167, lng: -86.1394 },
  Prominence: { lat: 30.2984, lng: -86.0783 },
  "WaterSound West Beach": { lat: 30.3013, lng: -86.0958 },
  "WaterSound Beach": { lat: 30.3028, lng: -86.0909 },
  "Seacrest Beach": { lat: 30.2787, lng: -86.0345 },
  "Rosemary Beach": { lat: 30.2759, lng: -86.0169 },
  "Alys Beach": { lat: 30.2768, lng: -86.0472 },
};

export const geoByArea: Record<string, { lat: number; lng: number }> = {
  "Dune Allen Beach": { lat: 30.3606, lng: -86.2794 },
  "Blue Mountain Beach": { lat: 30.3341, lng: -86.2142 },
  "Grayton Beach": { lat: 30.3284, lng: -86.1676 },
  "Seagrove Beach": { lat: 30.3131, lng: -86.1245 },
  "Seacrest Beach": { lat: 30.2787, lng: -86.0345 },
  "Rosemary / Inlet Beach": { lat: 30.2755, lng: -86.0129 },
  "Inlet Beach": { lat: 30.2752, lng: -86.0088 },
  "Santa Rosa Beach": { lat: 30.396, lng: -86.2288 },
  WaterSound: { lat: 30.3005, lng: -86.0904 },
  Seaside: { lat: 30.3234, lng: -86.1388 },
};

export const geoByRegion: Record<string, { lat: number; lng: number }> = {
  "West 30A": { lat: 30.3385, lng: -86.2114 },
  "Central 30A": { lat: 30.317, lng: -86.1353 },
  "East 30A": { lat: 30.2796, lng: -86.0298 },
};

export const homeHeroBackgroundImage =
  "https://30a.com/wp-content/uploads/2025/08/Alys-Beach-1.jpg";
