import beachEntryTexture from "@/assets/images/beach-entry.png";
import beachHomesTexture from "@/assets/images/beach-homes.jpg";
import beachPathTexture from "@/assets/images/beach-path.jpg";

export type DiscoverListing = {
  id: string;
  name: string;
  demoOrder: number;
  area: string;
  community: string;
  lat?: number;
  lng?: number;
  bedrooms: number;
  bathrooms: number;
  sleeps: number;
  kingBeds: number;
  queenBeds: number;
  privatePool: boolean;
  beachfront: boolean;
  golfCart: boolean;
  petsAllowed: boolean;
  accessible: boolean;
  elevator: boolean;
  previewImages: string[];
  typicalPrice: string;
};

export const googleMapsApiKey =
  (import.meta.env.GOOGLE_MAPS_JS_KEY as string | undefined) ??
  (import.meta.env.GOOGLE_MAPS_API_KEY as string | undefined) ??
  (import.meta.env.VITE_GOOGLE_MAPS_API_KEY as string | undefined);

export const sampleListings: DiscoverListing[] = [
  {
    id: "watercolor-62-royal-fern-way-248",
    name: "62 Royal Fern Way",
    demoOrder: 850899778,
    area: "Santa Rosa Beach",
    community: "WaterColor",
    lat: 30.3239,
    lng: -86.12606,
    bedrooms: 3,
    bathrooms: 2,
    sleeps: 6,
    kingBeds: 1,
    queenBeds: 2,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: true,
    accessible: false,
    elevator: false,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$6.9k - $9.2k",
  },
  {
    id: "rosemary-beach-red-stick-190-e-water-st-726",
    name: "Red Stick",
    demoOrder: 2797582160,
    area: "Rosemary Beach",
    community: "Rosemary Beach",
    lat: 30.28005,
    lng: -86.01352,
    bedrooms: 4,
    bathrooms: 4,
    sleeps: 11,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$7.6k - $9.9k",
  },
  {
    id: "seacrest-beach-toro-azul-59-green-st-784",
    name: "Toro Azul",
    demoOrder: 3750274172,
    area: "Seacrest Beach",
    community: "WaterSound Beach",
    lat: 30.28644,
    lng: -86.03955,
    bedrooms: 5,
    bathrooms: 5.5,
    sleeps: 12,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: true,
    beachfront: true,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$10.5k - $12.8k",
  },
  {
    id: "grayton-beach-bahama-breeze-148-gulf-shore-drive-407",
    name: "Bahama Breeze",
    demoOrder: 2903202531,
    area: "Grayton Beach",
    community: "Grayton Beach",
    lat: 30.33174,
    lng: -86.17681,
    bedrooms: 7,
    bathrooms: 6,
    sleeps: 25,
    kingBeds: 3,
    queenBeds: 2,
    privatePool: true,
    beachfront: true,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$11.9k - $14.2k",
  },
  {
    id: "watercolor-summer-house-memory-26-mist-flower-lane-1221",
    name: "Summer House Memory",
    demoOrder: 2094669407,
    area: "Santa Rosa Beach",
    community: "WaterColor",
    lat: 30.32658,
    lng: -86.139,
    bedrooms: 5,
    bathrooms: 5,
    sleeps: 12,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$8.3k - $10.6k",
  },
  {
    id: "watersound-30-a-ok-265-salt-box-lane-1349",
    name: "30-A-Ok",
    demoOrder: 2307675982,
    area: "WaterSound",
    community: "Seaside",
    lat: 30.30157,
    lng: -86.06821,
    bedrooms: 3,
    bathrooms: 4,
    sleeps: 8,
    kingBeds: 1,
    queenBeds: 2,
    privatePool: false,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$6.9k - $9.2k",
  },
  {
    id: "watercolor-sunny-side-up-568-east-royal-fern-way-1277",
    name: "Sunny Side Up",
    demoOrder: 626608498,
    area: "Santa Rosa Beach",
    community: "WaterColor",
    lat: 30.32754,
    lng: -86.1201,
    bedrooms: 5,
    bathrooms: 5,
    sleeps: 12,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$9.1k - $11.4k",
  },
  {
    id: "grayton-beach-grayton-bliss-120-banfill-street-167",
    name: "Grayton Bliss",
    demoOrder: 1572578457,
    area: "Grayton Beach",
    community: "Grayton Beach",
    lat: 30.32956,
    lng: -86.16405,
    bedrooms: 4,
    bathrooms: 5,
    sleeps: 12,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$7.6k - $9.9k",
  },
  {
    id: "seacrest-beach-the-chill-out-27-blue-dolphin-court-2945",
    name: "The Chill Out",
    demoOrder: 372165773,
    area: "Seacrest Beach",
    community: "Seacrest Beach",
    lat: 30.28324,
    lng: -86.02286,
    bedrooms: 4,
    bathrooms: 3.5,
    sleeps: 12,
    kingBeds: 2,
    queenBeds: 2,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$7.6k - $9.9k",
  },
  {
    id: "seagrove-beach-white-azaela-77-azalea-st-860",
    name: "White Azaela",
    demoOrder: 2486132372,
    area: "Seagrove Beach",
    community: "Seaside",
    lat: 30.31779,
    lng: -86.12749,
    bedrooms: 6,
    bathrooms: 5.5,
    sleeps: 18,
    kingBeds: 3,
    queenBeds: 2,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$9.8k - $12.1k",
  },
  {
    id: "seacrest-beach-three-little-birds-30-barefoot-lane-183",
    name: "Three Little Birds",
    demoOrder: 1203868157,
    area: "Seacrest Beach",
    community: "Seacrest Beach",
    lat: 30.28495,
    lng: -86.02091,
    bedrooms: 5,
    bathrooms: 5,
    sleeps: 16,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$9.1k - $11.4k",
  },
  {
    id: "watercolor-yolo-800-western-lake-1302",
    name: "Yolo",
    demoOrder: 1307807199,
    area: "Seaside",
    community: "WaterColor",
    lat: 30.32291,
    lng: -86.13887,
    bedrooms: 3,
    bathrooms: 4,
    sleeps: 10,
    kingBeds: 1,
    queenBeds: 2,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$6.9k - $9.2k",
  },
  {
    id: "seagrove-seasons-in-the-sun-140-dalton-drive-808",
    name: "Seasons in the Sun",
    demoOrder: 1335080198,
    area: "Seagrove Beach",
    community: "Seagrove Beach",
    lat: 30.31111,
    lng: -86.09674,
    bedrooms: 5,
    bathrooms: 6,
    sleeps: 12,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$9.1k - $11.4k",
  },
  {
    id: "blue-mountain-beach-serenity-dunes-299-old-beach-road-69",
    name: "Serenity Dunes",
    demoOrder: 1132705679,
    area: "Blue Mountain Beach",
    community: "Blue Mountain Beach",
    lat: 30.34349,
    lng: -86.21758,
    bedrooms: 5,
    bathrooms: 6,
    sleeps: 14,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$8.3k - $10.6k",
  },
  {
    id: "seacrest-beach-footprints-in-the-sand-36-kareny-lane-185",
    name: "Footprints in the Sand",
    demoOrder: 4102735866,
    area: "Seacrest Beach",
    community: "Seacrest Beach",
    lat: 30.29219,
    lng: -86.04834,
    bedrooms: 3,
    bathrooms: 3,
    sleeps: 8,
    kingBeds: 1,
    queenBeds: 2,
    privatePool: false,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$6.9k - $9.2k",
  },
  {
    id: "blue-mountain-66-s-spooky-lane-83",
    name: "66 S Spooky Lane",
    demoOrder: 541708157,
    area: "Blue Mountain Beach",
    community: "Blue Mountain Beach",
    lat: 30.34548,
    lng: -86.22633,
    bedrooms: 5,
    bathrooms: 7,
    sleeps: 12,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: true,
    beachfront: true,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: true,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$10.5k - $12.8k",
  },
  {
    id: "watersound-19-salt-box-lane-1336",
    name: "19 Salt Box Lane",
    demoOrder: 3181903707,
    area: "WaterSound",
    community: "WaterSound Beach",
    lat: 30.30414,
    lng: -86.0721,
    bedrooms: 5,
    bathrooms: 5.5,
    sleeps: 12,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: true,
    elevator: false,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$8.3k - $10.6k",
  },
  {
    id: "watercolor-421-western-lake-drive-1258",
    name: "421 Western Lake Drive",
    demoOrder: 1784887614,
    area: "Santa Rosa Beach",
    community: "WaterColor",
    lat: 30.32636,
    lng: -86.14379,
    bedrooms: 5,
    bathrooms: 5.5,
    sleeps: 12,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$8.3k - $10.6k",
  },
  {
    id: "watersound-45-tidal-bridge-way-1357",
    name: "45 Tidal Bridge Way",
    demoOrder: 153600318,
    area: "WaterSound",
    community: "WaterSound Beach",
    lat: 30.29708,
    lng: -86.06342,
    bedrooms: 5,
    bathrooms: 5.5,
    sleeps: 12,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$8.3k - $10.6k",
  },
  {
    id: "watercolor-beach-haven-604-western-lake-drive-1282",
    name: "Beach Haven",
    demoOrder: 780581720,
    area: "Santa Rosa Beach",
    community: "WaterColor",
    lat: 30.32405,
    lng: -86.14191,
    bedrooms: 4,
    bathrooms: 4,
    sleeps: 10,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$7.6k - $9.9k",
  },
  {
    id: "seagrove-how-sweet-it-is-15-lake-vista-lane-811",
    name: "How Sweet It Is",
    demoOrder: 3355366464,
    area: "Seagrove Beach",
    community: "Seagrove Beach",
    lat: 30.31024,
    lng: -86.10416,
    bedrooms: 4,
    bathrooms: 4.5,
    sleeps: 10,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: true,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$8.4k - $10.7k",
  },
  {
    id: "watercolor-searendipity-108-scrub-oak-circle-235",
    name: "Searendipity",
    demoOrder: 1050519288,
    area: "Santa Rosa Beach",
    community: "WaterColor",
    lat: 30.32663,
    lng: -86.13609,
    bedrooms: 4,
    bathrooms: 4.5,
    sleeps: 12,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$7.6k - $9.9k",
  },
  {
    id: "seagrove-beach-8-degrees-of-separation-45-sea-walk-circle-844",
    name: "8 Degrees of Separation",
    demoOrder: 1231697201,
    area: "Seagrove Beach",
    community: "Seaside",
    lat: 30.31352,
    lng: -86.11969,
    bedrooms: 8,
    bathrooms: 5.5,
    sleeps: 25,
    kingBeds: 4,
    queenBeds: 3,
    privatePool: true,
    beachfront: true,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$12.6k - $14.9k",
  },
  {
    id: "watercolor-white-sands-and-suntans-34-pine-needle-way-1242",
    name: "White Sands and Suntans",
    demoOrder: 201934588,
    area: "Santa Rosa Beach",
    community: "WaterColor",
    lat: 30.32681,
    lng: -86.12782,
    bedrooms: 4,
    bathrooms: 4,
    sleeps: 12,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$8.4k - $10.7k",
  },
  {
    id: "watersound-83-west-salt-box-lane-1368",
    name: "83 West Salt Box Lane",
    demoOrder: 1718236501,
    area: "WaterSound",
    community: "Seaside",
    lat: 30.30464,
    lng: -86.07303,
    bedrooms: 5,
    bathrooms: 6,
    sleeps: 16,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$9.1k - $11.4k",
  },
  {
    id: "watercolor-7th-heaven-82-flatwood-st-1306",
    name: "7th Heaven",
    demoOrder: 2341919784,
    area: "Santa Rosa Beach",
    community: "WaterColor",
    lat: 30.32751,
    lng: -86.13905,
    bedrooms: 5,
    bathrooms: 5.5,
    sleeps: 12,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$8.3k - $10.6k",
  },
  {
    id: "watersound-seaglass-152-e-yacht-pond-lane-1333",
    name: "Seaglass",
    demoOrder: 96745867,
    area: "WaterSound",
    community: "WaterSound Beach",
    lat: 30.30192,
    lng: -86.07021,
    bedrooms: 5,
    bathrooms: 5.5,
    sleeps: 12,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$9.1k - $11.4k",
  },
  {
    id: "rosemary-beach-living-the-dream-32-rosemary-avenue-main-house-2938",
    name: "Living the Dream",
    demoOrder: 2862328254,
    area: "Rosemary Beach",
    community: "Rosemary Beach",
    lat: 30.27903,
    lng: -86.01597,
    bedrooms: 4,
    bathrooms: 3.5,
    sleeps: 10,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$7.6k - $9.9k",
  },
  {
    id: "watercolor-happy-place-370-spartina-circle-1249",
    name: "Happy Place",
    demoOrder: 832165935,
    area: "Seaside",
    community: "WaterColor",
    lat: 30.32618,
    lng: -86.13303,
    bedrooms: 4,
    bathrooms: 3,
    sleeps: 10,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$7.6k - $9.9k",
  },
  {
    id: "watersound-time-of-your-life-86-compass-point-way-1370",
    name: "Time of Your Life",
    demoOrder: 2283344074,
    area: "WaterSound",
    community: "WaterSound Beach",
    lat: 30.30026,
    lng: -86.06954,
    bedrooms: 6,
    bathrooms: 6.5,
    sleeps: 14,
    kingBeds: 3,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$9.8k - $12.1k",
  },
  {
    id: "seagrove-beach-3036-east-county-highway-30a-2996",
    name: "3036 East County Highway 30A",
    demoOrder: 1902353087,
    area: "Seagrove Beach",
    community: "Seagrove Beach",
    lat: 30.31592,
    lng: -86.12607,
    bedrooms: 7,
    bathrooms: 7.5,
    sleeps: 20,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: true,
    beachfront: true,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: true,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$11.9k - $14.2k",
  },
  {
    id: "seagrove-beach-34-seagrove-village-dr-220",
    name: "34 Seagrove Village Dr",
    demoOrder: 1652539200,
    area: "Seagrove Beach",
    community: "Seaside",
    lat: 30.31888,
    lng: -86.12782,
    bedrooms: 4,
    bathrooms: 4,
    sleeps: 10,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$7.6k - $9.9k",
  },
  {
    id: "seagrove-beach-mia-s-place-22-south-gulf-drive-217",
    name: "Mia’s Place",
    demoOrder: 2038276969,
    area: "Seagrove Beach",
    community: "Seagrove Beach",
    lat: 30.31269,
    lng: -86.09633,
    bedrooms: 4,
    bathrooms: 4,
    sleeps: 10,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$8.4k - $10.7k",
  },
  {
    id: "watercolor-143-buttercup-st-1193",
    name: "143 Buttercup St",
    demoOrder: 2682903683,
    area: "Seaside",
    community: "WaterColor",
    lat: 30.32552,
    lng: -86.14342,
    bedrooms: 3,
    bathrooms: 3.5,
    sleeps: 10,
    kingBeds: 1,
    queenBeds: 2,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$6.9k - $9.2k",
  },
  {
    id: "seacrest-beach-sunny-shores-29-beachcomber-lane-182",
    name: "Sunny Shores",
    demoOrder: 3235496356,
    area: "Seacrest Beach",
    community: "Seacrest Beach",
    lat: 30.28464,
    lng: -86.02055,
    bedrooms: 3,
    bathrooms: 2.5,
    sleeps: 10,
    kingBeds: 1,
    queenBeds: 2,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$6.9k - $9.2k",
  },
  {
    id: "seacrest-beach-the-sea-shak-41-green-street-780",
    name: "The Sea Shak",
    demoOrder: 2196697574,
    area: "Seacrest Beach",
    community: "Seacrest Beach",
    lat: 30.28646,
    lng: -86.03917,
    bedrooms: 8,
    bathrooms: 8.5,
    sleeps: 24,
    kingBeds: 1,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: true,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$11.2k - $13.5k",
  },
  {
    id: "watercolor-241-red-cedar-way-1218",
    name: "241 Red Cedar Way",
    demoOrder: 496230098,
    area: "Santa Rosa Beach",
    community: "WaterColor",
    lat: 30.32486,
    lng: -86.13295,
    bedrooms: 7,
    bathrooms: 6.5,
    sleeps: 14,
    kingBeds: 3,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$9.7k - $12.0k",
  },
  {
    id: "watersound-seabatical-230-salt-box-lane-1343",
    name: "Seabatical",
    demoOrder: 307504342,
    area: "WaterSound",
    community: "WaterSound Beach",
    lat: 30.30195,
    lng: -86.0688,
    bedrooms: 3,
    bathrooms: 3,
    sleeps: 8,
    kingBeds: 1,
    queenBeds: 2,
    privatePool: false,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$6.9k - $9.2k",
  },
  {
    id: "watercolor-sea-la-vie-301-east-royal-fern-1234",
    name: "Sea-La-Vie",
    demoOrder: 2409884260,
    area: "Santa Rosa Beach",
    community: "WaterColor",
    lat: 30.32424,
    lng: -86.12157,
    bedrooms: 4,
    bathrooms: 4,
    sleeps: 8,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: true,
    beachfront: true,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$9.8k - $12.1k",
  },
  {
    id: "watercolor-79-dandelion-1297",
    name: "79 Dandelion",
    demoOrder: 920144257,
    area: "Santa Rosa Beach",
    community: "WaterColor",
    lat: 30.3241,
    lng: -86.13631,
    bedrooms: 6,
    bathrooms: 5,
    sleeps: 14,
    kingBeds: 3,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: true,
    elevator: false,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$9.0k - $11.3k",
  },
  {
    id: "grayton-beach-bella-waves-60-hotz-avenue-418",
    name: "Bella Waves",
    demoOrder: 325483733,
    area: "Grayton Beach",
    community: "Grayton Beach",
    lat: 30.32922,
    lng: -86.1656,
    bedrooms: 6,
    bathrooms: 8.5,
    sleeps: 20,
    kingBeds: 3,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: true,
    elevator: true,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$9.8k - $12.1k",
  },
  {
    id: "inlet-beach-somewhere-in-the-sun-15-pompano-street-172",
    name: "Somewhere in the Sun",
    demoOrder: 1603337400,
    area: "Inlet Beach",
    community: "Inlet Beach",
    lat: 30.275,
    lng: -86.00421,
    bedrooms: 4,
    bathrooms: 4.5,
    sleeps: 10,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$7.6k - $9.9k",
  },
  {
    id: "blue-mountain-beach-olive-at-the-beach-122-sand-dunes-137",
    name: "Olive at the Beach",
    demoOrder: 2518937714,
    area: "Blue Mountain Beach",
    community: "Blue Mountain Beach",
    lat: 30.33894,
    lng: -86.19978,
    bedrooms: 5,
    bathrooms: 4,
    sleeps: 14,
    kingBeds: 2,
    queenBeds: 1,
    privatePool: true,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$9.1k - $11.4k",
  },
  {
    id: "blue-mountain-beach-charmed-water-oasis-at-30a-190-walnut-street-142",
    name: "Charmed Water Oasis at 30a",
    demoOrder: 3683094995,
    area: "Blue Mountain Beach",
    community: "Blue Mountain Beach",
    lat: 30.35084,
    lng: -86.21804,
    bedrooms: 4,
    bathrooms: 4.5,
    sleeps: 8,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$8.4k - $10.7k",
  },
  {
    id: "watercolor-70-red-cedar-way-1290",
    name: "70 Red Cedar Way",
    demoOrder: 972087222,
    area: "Santa Rosa Beach",
    community: "WaterColor",
    lat: 30.327,
    lng: -86.13324,
    bedrooms: 4,
    bathrooms: 3,
    sleeps: 10,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$7.6k - $9.9k",
  },
  {
    id: "seacrest-beach-amazing-grace-8915-e-co-hwy-30a-796",
    name: "Amazing Grace",
    demoOrder: 2043315947,
    area: "Seacrest Beach",
    community: "Seacrest Beach",
    lat: 30.28784,
    lng: -86.04051,
    bedrooms: 8,
    bathrooms: 9.5,
    sleeps: 24,
    kingBeds: 4,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: true,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$11.2k - $13.5k",
  },
  {
    id: "watercolor-blessings-by-the-sea-160-e-royal-fern-way-1203",
    name: "Blessings by the Sea",
    demoOrder: 2201272248,
    area: "Seaside",
    community: "WaterColor",
    lat: 30.323,
    lng: -86.12307,
    bedrooms: 4,
    bathrooms: 4,
    sleeps: 10,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$8.4k - $10.7k",
  },
  {
    id: "watercolor-28-red-cedar-way-1227",
    name: "28 Red Cedar Way",
    demoOrder: 1371694252,
    area: "Seaside",
    community: "WaterColor",
    lat: 30.32726,
    lng: -86.13258,
    bedrooms: 4,
    bathrooms: 3.5,
    sleeps: 10,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$7.6k - $9.9k",
  },
  {
    id: "grayton-beach-resting-beach-face-277-barton-s-way-170",
    name: "Resting Beach Face",
    demoOrder: 3498087981,
    area: "Grayton Beach",
    community: "Grayton Beach",
    lat: 30.34045,
    lng: -86.19282,
    bedrooms: 5,
    bathrooms: 4.5,
    sleeps: 12,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$8.3k - $10.6k",
  },
  {
    id: "watercolor-magnolia-house-592-western-lake-drive-247",
    name: "Magnolia House",
    demoOrder: 1619442210,
    area: "Santa Rosa Beach",
    community: "WaterColor",
    lat: 30.32413,
    lng: -86.14208,
    bedrooms: 4,
    bathrooms: 4.5,
    sleeps: 10,
    kingBeds: 2,
    queenBeds: 1,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$7.6k - $9.9k",
  },
  {
    id: "seagrove-beach-chel-sea-lane-hideaway-80-chelsey-lane-2929",
    name: "Chel-SEA Lane Hideaway",
    demoOrder: 4150665553,
    area: "Seagrove Beach",
    community: "Seaside",
    lat: 30.32029,
    lng: -86.11706,
    bedrooms: 5,
    bathrooms: 5.5,
    sleeps: 18,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$9.1k - $11.4k",
  },
  {
    id: "watercolor-wispy-waters-73-western-lake-drive-1292",
    name: "Wispy Waters",
    demoOrder: 1663527609,
    area: "Seaside",
    community: "WaterColor",
    lat: 30.32252,
    lng: -86.14306,
    bedrooms: 5,
    bathrooms: 5.5,
    sleeps: 14,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$9.1k - $11.4k",
  },
  {
    id: "seagrove-beach-feeling-tipsea-67-montigo-avenue-851",
    name: "Feeling Tipsea",
    demoOrder: 941042679,
    area: "Seagrove Beach",
    community: "Seagrove Beach",
    lat: 30.31528,
    lng: -86.11829,
    bedrooms: 8,
    bathrooms: 8.5,
    sleeps: 26,
    kingBeds: 1,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: true,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$11.2k - $13.5k",
  },
  {
    id: "watercolor-214-spartina-circle-2818",
    name: "214 Spartina Circle",
    demoOrder: 135546740,
    area: "Santa Rosa Beach",
    community: "WaterColor",
    lat: 30.32642,
    lng: -86.13052,
    bedrooms: 3,
    bathrooms: 4,
    sleeps: 10,
    kingBeds: 1,
    queenBeds: 2,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$6.9k - $9.2k",
  },
  {
    id: "seacrest-beach-gotta-lovitt-150-walton-gulfview-drive-772",
    name: "Gotta Lovitt",
    demoOrder: 1284135594,
    area: "Seacrest Beach",
    community: "Seacrest Beach",
    lat: 30.28952,
    lng: -86.04186,
    bedrooms: 5,
    bathrooms: 5,
    sleeps: 14,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: true,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$9.1k - $11.4k",
  },
  {
    id: "seacrest-beach-heaven-on-30a-145-clareon-drive-771",
    name: "Heaven on 30A",
    demoOrder: 2259024663,
    area: "Seacrest Beach",
    community: "Seacrest Beach",
    lat: 30.29196,
    lng: -86.04802,
    bedrooms: 4,
    bathrooms: 5,
    sleeps: 18,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$8.4k - $10.7k",
  },
  {
    id: "blue-mountain-beach-drift-away-on-30a-35-kriss-court-2932",
    name: "Drift Away on 30A",
    demoOrder: 4233383844,
    area: "Blue Mountain Beach",
    community: "Blue Mountain Beach",
    lat: 30.3448,
    lng: -86.20176,
    bedrooms: 4,
    bathrooms: 3.5,
    sleeps: 8,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$7.6k - $9.9k",
  },
  {
    id: "rosemary-beach-171-e-kingston-road-715",
    name: "171 E Kingston Road",
    demoOrder: 3527080673,
    area: "Rosemary Beach",
    community: "Seaside",
    lat: 30.28107,
    lng: -86.01273,
    bedrooms: 3,
    bathrooms: 3,
    sleeps: 8,
    kingBeds: 1,
    queenBeds: 2,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$6.9k - $9.2k",
  },
  {
    id: "seagrove-beach-51-bramble-lane-223",
    name: "51 Bramble Lane",
    demoOrder: 3931848770,
    area: "Seagrove Beach",
    community: "WaterColor",
    lat: 30.32247,
    lng: -86.12675,
    bedrooms: 4,
    bathrooms: 4,
    sleeps: 10,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: true,
    elevator: true,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$7.6k - $9.9k",
  },
  {
    id: "watercolor-29-calamint-court-1230",
    name: "29 Calamint Court",
    demoOrder: 24116987,
    area: "Santa Rosa Beach",
    community: "WaterColor",
    lat: 30.32695,
    lng: -86.12706,
    bedrooms: 4,
    bathrooms: 4,
    sleeps: 12,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$7.6k - $9.9k",
  },
  {
    id: "seagrove-beach-whake-up-172-chivas-lane-815",
    name: "Whake Up",
    demoOrder: 419272841,
    area: "Seagrove Beach",
    community: "Seagrove Beach",
    lat: 30.30536,
    lng: -86.09125,
    bedrooms: 9,
    bathrooms: 9,
    sleeps: 34,
    kingBeds: 4,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: true,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$11.9k - $14.2k",
  },
  {
    id: "watercolor-healing-palms-295-west-lake-forest-drive-241",
    name: "Healing Palms",
    demoOrder: 2170873113,
    area: "Santa Rosa Beach",
    community: "WaterColor",
    lat: 30.32723,
    lng: -86.13087,
    bedrooms: 4,
    bathrooms: 4,
    sleeps: 12,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: true,
    petsAllowed: true,
    accessible: false,
    elevator: false,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$7.6k - $9.9k",
  },
  {
    id: "grayton-beach-grayt-dreams-and-graytness-158-grayton-village-road-2982",
    name: "Grayt Dreams",
    demoOrder: 2291559120,
    area: "Grayton Beach",
    community: "Grayton Beach",
    lat: 30.34389,
    lng: -86.16385,
    bedrooms: 22,
    bathrooms: 19,
    sleeps: 64,
    kingBeds: 11,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: true,
    accessible: false,
    elevator: true,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$21.0k - $23.3k",
  },
  {
    id: "naturewalk-unwind-by-the-gulf-897-sandgrass-way-177",
    name: "Unwind by the Gulf",
    demoOrder: 3018975239,
    area: "Santa Rosa Beach",
    community: "Santa Rosa Beach",
    lat: 30.32717,
    lng: -86.11647,
    bedrooms: 4,
    bathrooms: 3.5,
    sleeps: 10,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$7.6k - $9.9k",
  },
  {
    id: "watercolor-72-buttercup-street-1291",
    name: "72 Buttercup Street",
    demoOrder: 96551574,
    area: "Seaside",
    community: "WaterColor",
    lat: 30.32467,
    lng: -86.14423,
    bedrooms: 3,
    bathrooms: 3.5,
    sleeps: 9,
    kingBeds: 1,
    queenBeds: 2,
    privatePool: true,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$7.7k - $10.0k",
  },
  {
    id: "watercolor-mint-julep-378-western-lake-drive-1250",
    name: "Mint Julep",
    demoOrder: 1217702525,
    area: "Santa Rosa Beach",
    community: "WaterColor",
    lat: 30.32592,
    lng: -86.14453,
    bedrooms: 4,
    bathrooms: 4,
    sleeps: 10,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$7.6k - $9.9k",
  },
  {
    id: "rosemary-beach-the-beach-house-106-rosemary-avenue-2955",
    name: "The Beach House",
    demoOrder: 2432270180,
    area: "Rosemary Beach",
    community: "Rosemary Beach",
    lat: 30.27824,
    lng: -86.0152,
    bedrooms: 3,
    bathrooms: 3.5,
    sleeps: 9,
    kingBeds: 1,
    queenBeds: 2,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$6.9k - $9.2k",
  },
  {
    id: "seagrove-beach-freebird-seagrove-135-dogwood-street-805",
    name: "Freebird Seagrove",
    demoOrder: 3337851439,
    area: "Seagrove Beach",
    community: "Seaside",
    lat: 30.32014,
    lng: -86.13268,
    bedrooms: 7,
    bathrooms: 8.5,
    sleeps: 26,
    kingBeds: 3,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: true,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$10.5k - $12.8k",
  },
  {
    id: "blue-mountain-beach-surf-shack-34-seaward-drive-72",
    name: "Surf Shack",
    demoOrder: 3621833510,
    area: "Dune Allen Beach",
    community: "Dune Allen Beach",
    lat: 30.34655,
    lng: -86.228,
    bedrooms: 4,
    bathrooms: 4,
    sleeps: 12,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$8.4k - $10.7k",
  },
  {
    id: "watersound-west-beach-adventure-west-25-full-moon-lane-262",
    name: "Beach Adventure",
    demoOrder: 46471835,
    area: "Rosemary Beach",
    community: "Seaside",
    lat: 30.30925,
    lng: -86.08462,
    bedrooms: 4,
    bathrooms: 3,
    sleeps: 10,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$7.6k - $9.9k",
  },
  {
    id: "watersound-summer-wind-40-watch-tower-lane-1354",
    name: "Summer Wind",
    demoOrder: 2837217019,
    area: "Grayton Beach",
    community: "Seaside",
    lat: 30.30126,
    lng: -86.07266,
    bedrooms: 6,
    bathrooms: 5.5,
    sleeps: 14,
    kingBeds: 3,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: true,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$9.8k - $12.1k",
  },
  {
    id: "watercolor-outta-the-blue-32-bluestem-lane-1238",
    name: "Outta the Blue",
    demoOrder: 877771308,
    area: "Seaside",
    community: "WaterColor",
    lat: 30.3292,
    lng: -86.13914,
    bedrooms: 4,
    bathrooms: 4.5,
    sleeps: 12,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$7.6k - $9.9k",
  },
  {
    id: "grayton-beach-grayt-dreams-158-grayton-village-road-409",
    name: "Grayt Dreams",
    demoOrder: 3530049163,
    area: "Grayton Beach",
    community: "Grayton Beach",
    lat: 30.34405,
    lng: -86.16383,
    bedrooms: 11,
    bathrooms: 9.5,
    sleeps: 32,
    kingBeds: 5,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: true,
    accessible: false,
    elevator: true,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$13.3k - $15.6k",
  },
  {
    id: "seagrove-beach-the-salty-pelican-158-brown-street-810",
    name: "The Salty Pelican",
    demoOrder: 2847322468,
    area: "Seagrove Beach",
    community: "Seagrove Beach",
    lat: 30.31082,
    lng: -86.09881,
    bedrooms: 6,
    bathrooms: 5,
    sleeps: 18,
    kingBeds: 3,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$9.8k - $12.1k",
  },
  {
    id: "watercolor-102-vermillion-way-1155",
    name: "102 Vermillion Way",
    demoOrder: 3355534615,
    area: "Santa Rosa Beach",
    community: "WaterColor",
    lat: 30.32941,
    lng: -86.14132,
    bedrooms: 4,
    bathrooms: 4.5,
    sleeps: 12,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$7.6k - $9.9k",
  },
  {
    id: "blue-mountain-spooky-blues-48-n-spooky-lane-154",
    name: "Spooky Blues",
    demoOrder: 2272244037,
    area: "Blue Mountain Beach",
    community: "Blue Mountain Beach",
    lat: 30.34769,
    lng: -86.22559,
    bedrooms: 5,
    bathrooms: 5,
    sleeps: 16,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: true,
    elevator: true,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$9.1k - $11.4k",
  },
  {
    id: "seagrove-beach-fore-seasons-392-wood-beach-drive-221",
    name: "Fore Seasons",
    demoOrder: 713043217,
    area: "Seagrove Beach",
    community: "Seaside",
    lat: 30.32225,
    lng: -86.12393,
    bedrooms: 5,
    bathrooms: 3.5,
    sleeps: 16,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$9.1k - $11.4k",
  },
  {
    id: "watercolor-cove-hollow-house-142-cove-hollow-street-1192",
    name: "Cove Hollow House",
    demoOrder: 3288510364,
    area: "Santa Rosa Beach",
    community: "WaterColor",
    lat: 30.32923,
    lng: -86.13989,
    bedrooms: 4,
    bathrooms: 4.5,
    sleeps: 12,
    kingBeds: 2,
    queenBeds: 2,
    privatePool: false,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: true,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$7.6k - $9.9k",
  },
  {
    id: "watersound-serenity-breeze-224-e-yacht-pond-lane-1341",
    name: "Serenity Breeze",
    demoOrder: 3852959849,
    area: "WaterSound",
    community: "WaterSound Beach",
    lat: 30.30135,
    lng: -86.06921,
    bedrooms: 5,
    bathrooms: 5.5,
    sleeps: 12,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: true,
    elevator: true,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$9.1k - $11.4k",
  },
  {
    id: "watercolor-99-mystic-cobalt-street-1326",
    name: "99 Mystic Cobalt Street",
    demoOrder: 819774958,
    area: "Santa Rosa Beach",
    community: "WaterColor",
    lat: 30.32335,
    lng: -86.14268,
    bedrooms: 5,
    bathrooms: 5.5,
    sleeps: 12,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$8.3k - $10.6k",
  },
  {
    id: "seacrest-beach-shrimply-the-best-249-beach-bike-way-2823",
    name: "Shrimply The Best",
    demoOrder: 3900303762,
    area: "Seacrest Beach",
    community: "Seacrest Beach",
    lat: 30.28528,
    lng: -86.02103,
    bedrooms: 3,
    bathrooms: 2.5,
    sleeps: 8,
    kingBeds: 1,
    queenBeds: 2,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$6.9k - $9.2k",
  },
  {
    id: "seagrove-beach-seabelle-on-30a-239-sand-oaks-circle-219",
    name: "SeaBelle on 30A",
    demoOrder: 885237625,
    area: "Seagrove Beach",
    community: "WaterColor",
    lat: 30.31025,
    lng: -86.10384,
    bedrooms: 3,
    bathrooms: 3.5,
    sleeps: 7,
    kingBeds: 1,
    queenBeds: 2,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$6.9k - $9.2k",
  },
  {
    id: "watercolor-64-vermilion-way-1283",
    name: "64 Vermilion Way",
    demoOrder: 2605901519,
    area: "Santa Rosa Beach",
    community: "WaterColor",
    lat: 30.32908,
    lng: -86.14053,
    bedrooms: 5,
    bathrooms: 6.5,
    sleeps: 14,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$9.1k - $11.4k",
  },
  {
    id: "watersound-siena-by-the-sea-224-gulf-bridge-lane-1340",
    name: "Siena By The Sea",
    demoOrder: 3545553159,
    area: "WaterSound",
    community: "WaterSound Beach",
    lat: 30.29797,
    lng: -86.05979,
    bedrooms: 5,
    bathrooms: 5.5,
    sleeps: 12,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$9.1k - $11.4k",
  },
  {
    id: "seagrove-sunset-sands-3325-east-co-hwy-30a-833",
    name: "Sunset Sands",
    demoOrder: 2249840715,
    area: "Seagrove Beach",
    community: "Seagrove Beach",
    lat: 30.31511,
    lng: -86.12061,
    bedrooms: 7,
    bathrooms: 8,
    sleeps: 36,
    kingBeds: 3,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: true,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$10.5k - $12.8k",
  },
  {
    id: "watercolor-3-sisters-on-the-beach-93-park-row-lane-1321",
    name: "3 Sisters on the Beach",
    demoOrder: 4045577600,
    area: "Santa Rosa Beach",
    community: "WaterColor",
    lat: 30.32308,
    lng: -86.1461,
    bedrooms: 6,
    bathrooms: 6.5,
    sleeps: 12,
    kingBeds: 3,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$9.0k - $11.3k",
  },
  {
    id: "watercolor-the-way-we-like-it-27-running-oak-circle-1224",
    name: "The Way We Like It",
    demoOrder: 2553360157,
    area: "Santa Rosa Beach",
    community: "WaterColor",
    lat: 30.32306,
    lng: -86.12837,
    bedrooms: 6,
    bathrooms: 6.5,
    sleeps: 16,
    kingBeds: 1,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$9.8k - $12.1k",
  },
  {
    id: "seaside-suite-magnolia-i-ii-640-forest-street-233",
    name: "Suite Magnolia I & II",
    demoOrder: 2864590147,
    area: "Seaside",
    community: "Seaside",
    lat: 30.32258,
    lng: -86.13763,
    bedrooms: 4,
    bathrooms: 5,
    sleeps: 9,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$7.6k - $9.9k",
  },
  {
    id: "prominence-four-buoys-and-a-birdie-24-w-crabbing-hole-lane-178",
    name: "Four Buoys and a Birdie",
    demoOrder: 81305371,
    area: "Rosemary Beach",
    community: "Prominence",
    lat: 30.29956,
    lng: -86.06522,
    bedrooms: 4,
    bathrooms: 4.5,
    sleeps: 14,
    kingBeds: 2,
    queenBeds: 2,
    privatePool: false,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$7.6k - $9.9k",
  },
  {
    id: "watersound-moonstone-10-tidepool-lane-1329",
    name: "Moonstone",
    demoOrder: 2595259778,
    area: "WaterSound",
    community: "WaterSound Beach",
    lat: 30.30353,
    lng: -86.07219,
    bedrooms: 5,
    bathrooms: 5.5,
    sleeps: 12,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: true,
    petsAllowed: false,
    accessible: false,
    elevator: true,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$8.3k - $10.6k",
  },
  {
    id: "always-on-my-mind",
    name: "Always On My Mind",
    demoOrder: 2889134960,
    area: "Seacrest Beach",
    community: "Seacrest Beach",
    lat: 30.2888,
    lng: -86.04706,
    bedrooms: 5,
    bathrooms: 5,
    sleeps: 12,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: true,
    beachfront: true,
    golfCart: false,
    petsAllowed: false,
    accessible: true,
    elevator: true,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$10.5k - $12.8k",
  },
  {
    id: "21-hamilton-lane",
    name: "21 Hamilton Lane",
    demoOrder: 2110605509,
    area: "Rosemary Beach",
    community: "Seacrest Beach",
    lat: 30.28207,
    lng: -86.01404,
    bedrooms: 4,
    bathrooms: 3,
    sleeps: 10,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$7.6k - $9.9k",
  },
  {
    id: "the-pearl-on-grove",
    name: "The Pearl on Grove",
    demoOrder: 926624848,
    area: "Seagrove Beach",
    community: "WaterColor",
    lat: 30.31859,
    lng: -86.12951,
    bedrooms: 3,
    bathrooms: 3,
    sleeps: 8,
    kingBeds: 1,
    queenBeds: 2,
    privatePool: true,
    beachfront: true,
    golfCart: false,
    petsAllowed: false,
    accessible: false,
    elevator: false,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$9.1k - $11.4k",
  },
  {
    id: "dune-our-thing",
    name: "Dune Our Thing",
    demoOrder: 564688057,
    area: "Rosemary Beach",
    community: "Seacrest Beach",
    lat: 30.27298,
    lng: -86.00315,
    bedrooms: 4,
    bathrooms: 3,
    sleeps: 10,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: true,
    beachfront: false,
    golfCart: false,
    petsAllowed: false,
    accessible: true,
    elevator: false,
    previewImages: [beachHomesTexture, beachPathTexture, beachEntryTexture],
    typicalPrice: "$8.4k - $10.7k",
  },
  {
    id: "mariglo",
    name: "Mariglo",
    demoOrder: 3339836689,
    area: "Rosemary Beach",
    community: "Seaside",
    lat: 30.30898,
    lng: -86.08393,
    bedrooms: 3,
    bathrooms: 3,
    sleeps: 8,
    kingBeds: 1,
    queenBeds: 2,
    privatePool: false,
    beachfront: false,
    golfCart: false,
    petsAllowed: true,
    accessible: false,
    elevator: false,
    previewImages: [beachPathTexture, beachHomesTexture, beachEntryTexture],
    typicalPrice: "$6.9k - $9.2k",
  },
  {
    id: "the-odessa",
    name: "The Odessa",
    demoOrder: 478955644,
    area: "Seagrove Beach",
    community: "Seaside",
    lat: 30.30588,
    lng: -86.09448,
    bedrooms: 4,
    bathrooms: 5,
    sleeps: 12,
    kingBeds: 2,
    queenBeds: 3,
    privatePool: true,
    beachfront: true,
    golfCart: false,
    petsAllowed: false,
    accessible: true,
    elevator: true,
    previewImages: [beachEntryTexture, beachHomesTexture, beachPathTexture],
    typicalPrice: "$9.8k - $12.1k",
  },
];

export const known30AAreas = ["West 30A", "Central 30A", "East 30A"];

export const known30ACommunities = [
  "WaterColor",
  "Seaside",
  "Prominence",
  "WaterSound West Beach",
  "WaterSound Beach",
  "Seacrest Beach",
  "Alys Beach",
  "Rosemary Beach",
];

export const communityBeachAreaMap: Record<string, string> = {
  Seaside: "Seagrove Beach",
  WaterColor: "Seagrove Beach",
  "Seacrest Beach": "Seacrest Beach",
  "Rosemary Beach": "Rosemary / Inlet Beach",
  "Alys Beach": "Inlet Beach",
  "WaterSound Beach": "Inlet Beach",
  "Kaiya Beach Resort": "Inlet Beach",
};

export const geoByCommunity: Record<string, { lat: number; lng: number }> = {
  Seaside: { lat: 30.3234, lng: -86.1388 },
  WaterColor: { lat: 30.3167, lng: -86.1394 },
  Prominence: { lat: 30.2984, lng: -86.0783 },
  "WaterSound West Beach": { lat: 30.3013, lng: -86.0958 },
  "WaterSound Beach": { lat: 30.3028, lng: -86.0909 },
  "Seacrest Beach": { lat: 30.2787, lng: -86.0345 },
  "Rosemary Beach": { lat: 30.2759, lng: -86.0169 },
  "Alys Beach": { lat: 30.2768, lng: -86.0472 },
};

export const geoByArea: Record<string, { lat: number; lng: number }> = {
  "Dune Allen Beach": { lat: 30.3606, lng: -86.2794 },
  "Blue Mountain Beach": { lat: 30.3341, lng: -86.2142 },
  "Grayton Beach": { lat: 30.3284, lng: -86.1676 },
  "Seagrove Beach": { lat: 30.3131, lng: -86.1245 },
  "Seacrest Beach": { lat: 30.2787, lng: -86.0345 },
  "Rosemary / Inlet Beach": { lat: 30.2755, lng: -86.0129 },
  "Inlet Beach": { lat: 30.2752, lng: -86.0088 },
  "Santa Rosa Beach": { lat: 30.396, lng: -86.2288 },
  WaterSound: { lat: 30.3005, lng: -86.0904 },
  Seaside: { lat: 30.3234, lng: -86.1388 },
};

export const geoByRegion: Record<string, { lat: number; lng: number }> = {
  "West 30A": { lat: 30.3385, lng: -86.2114 },
  "Central 30A": { lat: 30.317, lng: -86.1353 },
  "East 30A": { lat: 30.2796, lng: -86.0298 },
};

export const homeHeroBackgroundImage =
  "https://30a.com/wp-content/uploads/2025/08/Alys-Beach-1.jpg";
