/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LogoCaptureRouteImport } from './routes/logo-capture'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevListingRefinementRouteImport } from './routes/dev/listing-refinement'
import { Route as ApiSessionRouteImport } from './routes/api/session'
import { Route as ApiLogoutRouteImport } from './routes/api/logout'
import { Route as ApiLoginRouteImport } from './routes/api/login'
import { Route as DiscoverListingSlugRouteImport } from './routes/discover.listing.$slug'
import { Route as ApiDiscoverListingsRouteImport } from './routes/api/discover/listings'
import { Route as ApiDevListingRefinementRouteImport } from './routes/api/dev/listing-refinement'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDiscoverListingsSlugRouteImport } from './routes/api/discover/listings/$slug'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoCaptureRoute = LogoCaptureRouteImport.update({
  id: '/logo-capture',
  path: '/logo-capture',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevListingRefinementRoute = DevListingRefinementRouteImport.update({
  id: '/dev/listing-refinement',
  path: '/dev/listing-refinement',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionRoute = ApiSessionRouteImport.update({
  id: '/api/session',
  path: '/api/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogoutRoute = ApiLogoutRouteImport.update({
  id: '/api/logout',
  path: '/api/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoginRoute = ApiLoginRouteImport.update({
  id: '/api/login',
  path: '/api/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverListingSlugRoute = DiscoverListingSlugRouteImport.update({
  id: '/listing/$slug',
  path: '/listing/$slug',
  getParentRoute: () => DiscoverRoute,
} as any)
const ApiDiscoverListingsRoute = ApiDiscoverListingsRouteImport.update({
  id: '/api/discover/listings',
  path: '/api/discover/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevListingRefinementRoute = ApiDevListingRefinementRouteImport.update({
  id: '/api/dev/listing-refinement',
  path: '/api/dev/listing-refinement',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscoverListingsSlugRoute = ApiDiscoverListingsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiDiscoverListingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/logo-capture': typeof LogoCaptureRoute
  '/logout': typeof LogoutRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/session': typeof ApiSessionRoute
  '/dev/listing-refinement': typeof DevListingRefinementRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dev/listing-refinement': typeof ApiDevListingRefinementRoute
  '/api/discover/listings': typeof ApiDiscoverListingsRouteWithChildren
  '/discover/listing/$slug': typeof DiscoverListingSlugRoute
  '/api/discover/listings/$slug': typeof ApiDiscoverListingsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/logo-capture': typeof LogoCaptureRoute
  '/logout': typeof LogoutRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/session': typeof ApiSessionRoute
  '/dev/listing-refinement': typeof DevListingRefinementRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dev/listing-refinement': typeof ApiDevListingRefinementRoute
  '/api/discover/listings': typeof ApiDiscoverListingsRouteWithChildren
  '/discover/listing/$slug': typeof DiscoverListingSlugRoute
  '/api/discover/listings/$slug': typeof ApiDiscoverListingsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/logo-capture': typeof LogoCaptureRoute
  '/logout': typeof LogoutRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/session': typeof ApiSessionRoute
  '/dev/listing-refinement': typeof DevListingRefinementRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dev/listing-refinement': typeof ApiDevListingRefinementRoute
  '/api/discover/listings': typeof ApiDiscoverListingsRouteWithChildren
  '/discover/listing/$slug': typeof DiscoverListingSlugRoute
  '/api/discover/listings/$slug': typeof ApiDiscoverListingsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/home'
    | '/login'
    | '/logo-capture'
    | '/logout'
    | '/api/login'
    | '/api/logout'
    | '/api/session'
    | '/dev/listing-refinement'
    | '/api/auth/$'
    | '/api/dev/listing-refinement'
    | '/api/discover/listings'
    | '/discover/listing/$slug'
    | '/api/discover/listings/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/home'
    | '/login'
    | '/logo-capture'
    | '/logout'
    | '/api/login'
    | '/api/logout'
    | '/api/session'
    | '/dev/listing-refinement'
    | '/api/auth/$'
    | '/api/dev/listing-refinement'
    | '/api/discover/listings'
    | '/discover/listing/$slug'
    | '/api/discover/listings/$slug'
  id:
    | '__root__'
    | '/'
    | '/discover'
    | '/home'
    | '/login'
    | '/logo-capture'
    | '/logout'
    | '/api/login'
    | '/api/logout'
    | '/api/session'
    | '/dev/listing-refinement'
    | '/api/auth/$'
    | '/api/dev/listing-refinement'
    | '/api/discover/listings'
    | '/discover/listing/$slug'
    | '/api/discover/listings/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverRoute: typeof DiscoverRouteWithChildren
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  LogoCaptureRoute: typeof LogoCaptureRoute
  LogoutRoute: typeof LogoutRoute
  ApiLoginRoute: typeof ApiLoginRoute
  ApiLogoutRoute: typeof ApiLogoutRoute
  ApiSessionRoute: typeof ApiSessionRoute
  DevListingRefinementRoute: typeof DevListingRefinementRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDevListingRefinementRoute: typeof ApiDevListingRefinementRoute
  ApiDiscoverListingsRoute: typeof ApiDiscoverListingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logo-capture': {
      id: '/logo-capture'
      path: '/logo-capture'
      fullPath: '/logo-capture'
      preLoaderRoute: typeof LogoCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/listing-refinement': {
      id: '/dev/listing-refinement'
      path: '/dev/listing-refinement'
      fullPath: '/dev/listing-refinement'
      preLoaderRoute: typeof DevListingRefinementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session': {
      id: '/api/session'
      path: '/api/session'
      fullPath: '/api/session'
      preLoaderRoute: typeof ApiSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logout': {
      id: '/api/logout'
      path: '/api/logout'
      fullPath: '/api/logout'
      preLoaderRoute: typeof ApiLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/login': {
      id: '/api/login'
      path: '/api/login'
      fullPath: '/api/login'
      preLoaderRoute: typeof ApiLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/listing/$slug': {
      id: '/discover/listing/$slug'
      path: '/listing/$slug'
      fullPath: '/discover/listing/$slug'
      preLoaderRoute: typeof DiscoverListingSlugRouteImport
      parentRoute: typeof DiscoverRoute
    }
    '/api/discover/listings': {
      id: '/api/discover/listings'
      path: '/api/discover/listings'
      fullPath: '/api/discover/listings'
      preLoaderRoute: typeof ApiDiscoverListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/listing-refinement': {
      id: '/api/dev/listing-refinement'
      path: '/api/dev/listing-refinement'
      fullPath: '/api/dev/listing-refinement'
      preLoaderRoute: typeof ApiDevListingRefinementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discover/listings/$slug': {
      id: '/api/discover/listings/$slug'
      path: '/$slug'
      fullPath: '/api/discover/listings/$slug'
      preLoaderRoute: typeof ApiDiscoverListingsSlugRouteImport
      parentRoute: typeof ApiDiscoverListingsRoute
    }
  }
}

interface DiscoverRouteChildren {
  DiscoverListingSlugRoute: typeof DiscoverListingSlugRoute
}

const DiscoverRouteChildren: DiscoverRouteChildren = {
  DiscoverListingSlugRoute: DiscoverListingSlugRoute,
}

const DiscoverRouteWithChildren = DiscoverRoute._addFileChildren(
  DiscoverRouteChildren,
)

interface ApiDiscoverListingsRouteChildren {
  ApiDiscoverListingsSlugRoute: typeof ApiDiscoverListingsSlugRoute
}

const ApiDiscoverListingsRouteChildren: ApiDiscoverListingsRouteChildren = {
  ApiDiscoverListingsSlugRoute: ApiDiscoverListingsSlugRoute,
}

const ApiDiscoverListingsRouteWithChildren =
  ApiDiscoverListingsRoute._addFileChildren(ApiDiscoverListingsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverRoute: DiscoverRouteWithChildren,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  LogoCaptureRoute: LogoCaptureRoute,
  LogoutRoute: LogoutRoute,
  ApiLoginRoute: ApiLoginRoute,
  ApiLogoutRoute: ApiLogoutRoute,
  ApiSessionRoute: ApiSessionRoute,
  DevListingRefinementRoute: DevListingRefinementRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDevListingRefinementRoute: ApiDevListingRefinementRoute,
  ApiDiscoverListingsRoute: ApiDiscoverListingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
